### Recuperar todas las peliculas
GET http://localhost:3000/movies

### Recuperar una pelicula por ID
GET http://localhost:3000/movies/241bf55d-b649-4109-af7c-0e6890ded3fc

### Recuperar todas las peliculas por un genero
GET http://localhost:3000/movies?genre=action

### Crear una película
POST http://localhost:3000/movies
Content-Type: application/json

{
    "title": "The Godfather",
    "year": 1972,
    "director": "Francis Ford Coppola",
    "duration": 175,
    "poster": "https://i.imgur.com/Uzvny9I.jpg",
    "genre": [
        "Fantasy", 
        "Drama", 
        "Action"
    ],
    "rate": 9.2
}

### Actualizar una película (solo una parte de la película)

PATCH http://localhost:3000/movies/dcdd0fad-a94c-4810-8acc-5f108d3b18c3
Content-Type: application/json

{
    "title": "El patron",
    "year": 2006
}